
library(igraph)
library("isa2")
library("foreach")
library("doMC")
library(igarph)
library(igraph)
data.exp = read.table("/ngsprojects/iwt/ehsab/Gene_duplication/Integrated CORNET2.0/Integrated_SD.txt", colClasses = "numeric", nrows = 19285, comment.char = "", header = T)
condition.names = read.table("/ngsprojects/iwt/ehsab/Gene_duplication/Integrated_CORNET2.0/condition_name.txt", header = T)
NAME = names(table(condition.names))
NAME = NAME[-4]
# paralogous = read.table("~/Gene_duplication/Seed_genes/paralogous_total.txt", header = T)
paralogous = read.table("~/Gene_duplication/Seed_genes/paralogous_NoFilter.txt", header = T)
k = 1
load(paste("/ngsprojects/iwt/ehsab/Gene_duplication/Results/SA/Gene_score/Compendium_wise/",NAME[k],"/Graph_V2_95.RData", sep = ""))
library(igraph)
library(foreach)
library(doMC)
registerDoMC(5)
g
Score = matrix(NA, nrow(paralogous), 7)
colnames(Score) = c("Gene", "Paralogous", "Paralogous.cluster", "Gene.cluster.size", "Paralogous.cluster.size", "Cluster.overlap", "Paralogous.withi")
Score = as.data.frame(Score)
for (m in 1:nrow(paralogous)) {
# print(m)
i = paralogous[m,1]
j = paralogous[m,2]
memb.comun = data.frame("Ref" = neighborhood(g, 1, i, mode = c("out"))[[1]])
memb.comun.para = merge(memb.comun, paralogous, by = "Ref")
memb.comun.para.size = nrow(memb.comun.para)
Score[m, "Gene"] = i
Score[m, "Paralogous"] = j
Score[m, "Paralogous.cluster"] = length(intersect(neighborhood(g, 1, j, mode = c("out"))[[1]], memb.comun.para$Anch))
Score[m, "Paralogous.withi"] = nrow(paralogous[paralogous$Ref %in% neighborhood(g, 1, j, mode = c("out"))[[1]],])
Score[m, "Cluster.overlap"] = length(intersect(neighborhood(g, 1, j, mode = c("out"))[[1]], neighborhood(g, 1, i, mode = c("out"))[[1]]))
Score[m, "Gene.cluster.size"] = dim(memb.comun)[1]
Score[m, "Paralogous.cluster.size"] = length(neighborhood(g, 1, j, mode = c("out"))[[1]])
}
Score["Normalized.Paralogous.cluster"] = Score$Paralogous.cluster/(Score$Gene.cluster.size + Score$Paralogous.cluster.size)
Score["Normalized.Paralogous.cluster.Gene"] = Score$Paralogous.cluster/memb.comun.para.size
Score["Normalized.Paralogous.whitin.Gene"] = memb.comun.para.size/Score$Gene.cluster.size
Score["Normalized.Paralogous.cluster.Paralogous"] = Score$Paralogous.cluster/Score$Paralogous.withi
Score["Normalized.Paralogous.whitin.Paralogous"] = Score$Paralogous.withi/Score$Paralogous.cluster.size
Score["Jaccard"] = Score$Cluster.overlap/(Score$Gene.cluster.size + Score$Paralogous.cluster.size)
Score["Jaccard2"] = (Score$Cluster.overlap + 0.0001)/(Score$Gene.cluster.size + Score$Paralogous.cluster.size)
Score[is.na(Score)] = 0
write.table(Score, file = paste("/scratch/iwt/ehsab/Gene_duplication/Results/SA/Local/Compendium_wise/",NAME[k],"/Score95/Scores_V2/Anch_Score.txt", sep = ""), row.names = F, quote = F, sep = "\t")
write.table(Score, file = paste("/scratch/iwt/ehsab/Gene_duplication/Results/SA/Local/Compendium_wise/",NAME[k],"/Score95/Anch/Scores_V2/Anch_Score.txt", sep = ""), row.names = F, quote = F, sep = "\t")
dim(Score)
head(Score)
hist(Score$Jaccard)
hist(Score$Jaccard * 2, breaks = 100)
Score99 = read.delim("/scratch/iwt/ehsab/Gene_duplication/Results/SA/Local/Compendium_wise/abiotic/Score99/Scores_V2/Anch_Score.txt")
hist(Score99$Jaccard * 2)
hist(Score99$Jaccard * 2, breaks = 100)
library(ggplot2)
Hist = rbind(data.frame("Jaccard" = Score$Jaccard, "Group" = 95), data.frame("Jaccard" = Score99$Jaccard, "Group" = 99))
head(Hist)
Hist = rbind(data.frame("Jaccard" = Score$Jaccard, "Cluster.size" = Score$Paralogous.cluster.size, "Group" = 95), data.frame("Jaccard" = Score99$Jaccard, "Cluster.size" = Score99$Paralogous.cluster.size, "Group" = 99))
head(Hist)
Hist = rbind(data.frame("Jaccard" = Score$Jaccard, "Cluster.size" = Score$Paralogous.cluster.size, "Group" = 95, "Shared_anchor" = Score$Paralogous.cluster), data.frame("Jaccard" = Score99$Jaccard, "Cluster.size" = Score99$Paralogous.cluster.size, "Group" = 99, "Shared_anchor" = Score99$Paralogous.cluster))
head(Hist)
ggplot(Hist, aes(x = Jaccrd, fill = Group)) + geom_density()
ggplot(Hist, aes(x = Jaccard, fill = Group)) + geom_density()
class(Hist)
ggplot(Hist, aes(x = Jaccard, fill = factor(Group))) + geom_density()
ggplot(Hist, aes(x = Jaccard, fill = factor(Group))) + geom_histogram()
ggplot(Hist, aes(x = Cluster.size, fill = factor(Group))) + geom_density()
ggplot(Hist, aes(x = Shared_anchor, fill = factor(Group))) + geom_density()
head(Score)
head(Score99)
Scatter = cbind(Score, Score99)
head(Scatter)
Scatter = cbind(Score[, c("Paralogous.cluster.size", "Paralogous.cluster", "Jaccard", "Normalized.Paralogous.cluster")], Score99[, c("Paralogous.cluster.size", "Paralogous.cluster", "Jaccard", "Normalized.Paralogous.cluster")])
head(Scatter)
Scatter = cbind("95" = Score[, c("Paralogous.cluster.size", "Paralogous.cluster", "Jaccard", "Normalized.Paralogous.cluster")], Score99[, c("Paralogous.cluster.size", "Paralogous.cluster", "Jaccard", "Normalized.Paralogous.cluster")])
head(Scatter)
ggplot(Scatter, aes(x = 95.Paralogous.cluster.size, y = Paralogous.cluster.size)) + geom_dotplot()
ggplot(Scatter, aes(x = 95.Paralogous.cluster.size, y = Paralogous.cluster.size)) + geom_point()
ggplot(Scatter, aes(x = Paralogous.cluster.size, y = Paralogous.cluster.size)) + geom_point()
ggplot(Scatter, aes(x = Paralogous.cluster.size, y = 95.Paralogous.cluster.size)) + geom_point()
Scatter = cbind("N95" = Score[, c("Paralogous.cluster.size", "Paralogous.cluster", "Jaccard", "Normalized.Paralogous.cluster")], Score99[, c("Paralogous.cluster.size", "Paralogous.cluster", "Jaccard", "Normalized.Paralogous.cluster")])
ggplot(Scatter, aes(x = Paralogous.cluster.size, y = N95.Paralogous.cluster.size)) + geom_point()
ggplot(Scatter, aes(x = Paralogous.cluster.size, y = N95.Paralogous.cluster.size)) + geom_point() + geom_abline(intercept=0, slope=1)
ggplot(Scatter, aes(x = Paralogous.cluster.size, y = N95.Paralogous.cluster.size)) + geom_point() + geom_abline(intercept=0, slope=1) + scale_y_continuous(limits = c(0, 200))
ggplot(Scatter, aes(x = Paralogous.cluster.size, y = N95.Paralogous.cluster.size)) + geom_point() + geom_abline(intercept=0, slope=1) + scale_y_continuous(limits = c(0, 2000))
ggplot(Scatter, aes(x = Paralogous.cluster.size, y = N95.Paralogous.cluster.size)) + geom_point() + geom_abline(intercept=0, slope=1) + scale_y_continuous(limits = c(0, 2000)) + scale_x_continuous(limits = c(0, 2000))
ggplot(Scatter, aes(x = Paralogous.cluster.size, y = N95.Paralogous.cluster.size)) + geom_point() + geom_abline(intercept=0, slope=1) + scale_y_continuous(limits = c(0, 2000))
ggplot(Scatter, aes(x = Paralogous.cluster.size, y = N95.Paralogous.cluster.size)) + geom_point() + geom_abline(intercept=0, slope=1) + scale_y_continuous(limits = c(0, 2000)) + xlab("csluter size 99 percent")+ ylab("cluster size 95 percent")
jpeg("/scratch/iwt/ehsab/Gene_duplication/Results/SA/Compare_SA__permut_thresold/abiotic/ClusterSizeScatter.jpeg")
ggplot(Scatter, aes(x = Paralogous.cluster.size, y = N95.Paralogous.cluster.size)) + geom_point() + geom_abline(intercept=0, slope=1) + scale_y_continuous(limits = c(0, 2000)) + xlab("csluter size 99 percent")+ ylab("cluster size 95 percent")
dev.off()
jpeg("/scratch/iwt/ehsab/Gene_duplication/Results/SA/Compare_SA__permut_thresold/abiotic/ClusterSizeScatter.jpeg", width=8, height=5, units="in", res=100, pointsize = 5)
ggplot(Scatter, aes(x = Paralogous.cluster.size, y = N95.Paralogous.cluster.size)) + geom_point() + geom_abline(intercept=0, slope=1) + scale_y_continuous(limits = c(0, 2000)) + xlab("csluter size 99 percent")+ ylab("cluster size 95 percent")
dev.off()
head(Hist)
ggplot(Hist, aes(x = Cluster.size, fill = factor(Group))) + geom_density()
ggplot(Hist, aes(x = Cluster.size, fill = factor(Group))) + geom_density(alpha = 0.5)
jpeg("/scratch/iwt/ehsab/Gene_duplication/Results/SA/Compare_SA__permut_thresold/abiotic/ClusterSizeDensity.jpeg", width=8, height=5, units="in", res=100, pointsize = 5)
ggplot(Hist, aes(x = Cluster.size, fill = factor(Group))) + geom_density(alpha = 0.5)
dev.off()
aggregate(Hist$Cluster.size, FUN = quantile)
aggregate(Hist$Cluster.size, by = Group, FUN = quantile)
aggregate(Hist$Cluster.size, by = Hist$Group, FUN = quantile)
aggregate(Hist$Cluster.size, by = list(Hist$Group), FUN = quantile)
Hist = rbind(data.frame("Jaccard" = Score$Jaccard, "Cluster.size" = Score$Paralogous.cluster.size, "Group" = 95, "Shared_anchor" = Score$Paralogous.cluster, "NormShared" = Score$Normalized.Paralogous.cluster)), data.frame("Jaccard" = Score99$Jaccard, "Cluster.size" = Score99$Paralogous.cluster.size, "Group" = 99, "Shared_anchor" = Score99$Paralogous.cluster, "NormShared" = Score99$Normalized.Paralogous.cluster))
Hist = rbind(data.frame("Jaccard" = Score$Jaccard, "Cluster.size" = Score$Paralogous.cluster.size, "Group" = 95, "Shared_anchor" = Score$Paralogous.cluster, "NormShared" = Score$Normalized.Paralogous.cluster), data.frame("Jaccard" = Score99$Jaccard, "Cluster.size" = Score99$Paralogous.cluster.size, "Group" = 99, "Shared_anchor" = Score99$Paralogous.cluster, "NormShared" = Score99$Normalized.Paralogous.cluster))
head(Hist)
aggregate(Hist$NormShared, by = list(Hist$Group), FUN = quantile)
jpeg("/scratch/iwt/ehsab/Gene_duplication/Results/SA/Compare_SA__permut_thresold/abiotic/SharedAnchNormScatter.jpeg")
ggplot(Scatter, aes(x = Normalized.Paralogous.cluster, y = N95.Normalized.Paralogous.cluster)) + geom_point() + geom_abline(intercept=0, slope=1) + scale_y_continuous(limits = c(0, 2000)) + xlab("Normalized shared anchorpints 99 percent")+ ylab("Normalized shared anchorpints 95 percent")
dev.off()
head(Scatter)
ggplot(Scatter, aes(x = Normalized.Paralogous.cluster, y = N95.Normalized.Paralogous.cluster)) + geom_point() + geom_abline(intercept=0, slope=1) + scale_y_continuous(limits = c(0, 2000)) + xlab("Normalized shared anchorpints 99 percent")+ ylab("Normalized shared anchorpints 95 percent")
Scatter$N95.Normalized.Paralogous.cluster
hist(Scatter$N95.Normalized.Paralogous.cluster)
ggplot(Scatter, aes(x = Normalized.Paralogous.cluster, y = N95.Normalized.Paralogous.cluster)) + geom_point() + geom_abline(intercept=0, slope=1) + scale_y_continuous(limits = c(0, 1)) + xlab("Normalized shared anchorpints 99 percent")+ ylab("Normalized shared anchorpints 95 percent")
ggplot(Scatter, aes(x = Normalized.Paralogous.cluster, y = N95.Normalized.Paralogous.cluster)) + geom_point() + geom_abline(intercept=0, slope=1)  + xlab("Normalized shared anchorpints 99 percent")+ ylab("Normalized shared anchorpints 95 percent")
head(Scatter)
ggplot(Scatter, aes(x = Paralogous.cluster, y = N95.Paralogous.cluster)) + geom_point() + geom_abline(intercept=0, slope=1)  + xlab("Normalized shared anchorpints 99 percent")+ ylab("Normalized shared anchorpints 95 percent")
jpeg("/scratch/iwt/ehsab/Gene_duplication/Results/SA/Compare_SA__permut_thresold/abiotic/SharedAnchNormScatter.jpeg")
ggplot(Scatter, aes(x = Paralogous.cluster, y = N95.Paralogous.cluster)) + geom_point() + geom_abline(intercept=0, slope=1)  + xlab("Shared anchorpints 99 percent")+ ylab("Shared anchorpints 95 percent")
dev.off()
jpeg("/scratch/iwt/ehsab/Gene_duplication/Results/SA/Compare_SA__permut_thresold/abiotic/SharedAnchScatter.jpeg", width=8, height=5, units="in", res=100, pointsize = 5)
ggplot(Scatter, aes(x = Paralogous.cluster, y = N95.Paralogous.cluster)) + geom_point() + geom_abline(intercept=0, slope=1)  + xlab("Shared anchorpints 99 percent")+ ylab("Shared anchorpints 95 percent")
dev.off()
aggregate(Hist$NormShared, by = list(Hist$Group), FUN = quantile)
head(Hist)
aggregate(Hist$Shared_anchor, by = list(Hist$Group), FUN = quantile)
ggplot(Hist, aes(x = Shared_anchor, fill = factor(Group))) + geom_density(alpha = 0.5)
ggplot(Hist, aes(x = Shared_anchor, fill = factor(Group))) + geom_boxplot()
ggplot(Hist, aes(factor(Group), Shared_anchor) + geom_boxplot()
ggplot(Hist, aes(factor(Group), Shared_anchor)) + geom_boxplot()
ggplot(Hist, aes(factor(Group), Shared_anchor)) + geom_boxplot(notch = TRUE)
ggplot(Hist, aes(factor(Group), Shared_anchor)) + geom_violin() + geom_jitter(height = 0)
ggplot(Hist, aes(factor(Group), Shared_anchor)) + geom_violin() + geom_jitter()
ggplot(Hist, aes(factor(Group), Shared_anchor)) + geom_violin() 
?geom_violin
ggplot(Hist, aes(factor(Group), Shared_anchor)) + geom_violin(scale = "count") 
ggplot(Hist, aes(factor(Group), Shared_anchor)) + geom_violin(aes(fill = factor(Group))) 
ggplot(Hist, aes(factor(Group), Shared_anchor)) + geom_violin(aes(fill = factor(Group))) + geom_jitter(height = 0)
jpeg("/scratch/iwt/ehsab/Gene_duplication/Results/SA/Compare_SA__permut_thresold/abiotic/SharedAnchDistribution.jpeg", width=8, height=5, units="in", res=100, pointsize = 5)
ggplot(Hist, aes(factor(Group), Shared_anchor)) + geom_violin(aes(fill = factor(Group))) + geom_jitter(height = 0) + xlab("Threshold") + ylab("Shared anchorpoints")
dev.off()
ggplot(Scatter, aes(x = Jaccard, y = N95.Jaccard)) + geom_point() + geom_abline(intercept=0, slope=1)  + xlab("Shared anchorpints 99 percent")+ ylab("Shared anchorpints 95 percent")
jpeg("/scratch/iwt/ehsab/Gene_duplication/Results/SA/Compare_SA__permut_thresold/abiotic/JaccardScatter.jpeg", width=8, height=5, units="in", res=100, pointsize = 5)
ggplot(Scatter, aes(x = Jaccard, y = N95.Jaccard)) + geom_point() + geom_abline(intercept=0, slope=1)  + xlab("Jaccard 99 percent")+ ylab("Jaccard 95 percent")
dev.off()
ggplot(Scatter, aes(x = Jaccard * 2, y = N95.Jaccard * 2)) + geom_point() + geom_abline(intercept=0, slope=1)  + xlab("Jaccard 99 percent")+ ylab("Jaccard 95 percent")
jpeg("/scratch/iwt/ehsab/Gene_duplication/Results/SA/Compare_SA__permut_thresold/abiotic/JaccardScatter.jpeg", width=8, height=5, units="in", res=100, pointsize = 5)
ggplot(Scatter, aes(x = Jaccard * 2, y = N95.Jaccard * 2)) + geom_point() + geom_abline(intercept=0, slope=1)  + xlab("Jaccard 99 percent")+ ylab("Jaccard 95 percent")
dev.off()
ggplot(Hist, aes(x = Jaccard * 2, fill = factor(Group))) + geom_density(alpha = 0.5)
ggplot(Hist, aes(factor(Group), Jaccard * 2)) + geom_violin(aes(fill = factor(Group))) + geom_jitter(height = 0) + xlab("Threshold") + ylab("Shared anchorpoints")
head(Hist)
HistMod = Hist[Hist$Cluster.size > 2, ]
head(HistMod)
dim(HistMod)
dim(Hist)
ggplot(HistMod, aes(factor(Group), Jaccard * 2)) + geom_violin(aes(fill = factor(Group))) + geom_jitter(height = 0) + xlab("Threshold") + ylab("Shared anchorpoints")
ggplot(Hist, aes(x = Jaccard * 2, fill = factor(Group))) + geom_density(alpha = 0.5)
ggplot(HistMod, aes(x = Jaccard * 2, fill = factor(Group))) + geom_density(alpha = 0.5)
jpeg("/scratch/iwt/ehsab/Gene_duplication/Results/SA/Compare_SA__permut_thresold/abiotic/JaccardDensity.jpeg", width=8, height=5, units="in", res=100, pointsize = 5)
ggplot(HistMod, aes(x = Jaccard * 2, fill = factor(Group))) + geom_density(alpha = 0.5) + xlab("Jaccard")
dev.off()
aggregate(HistMod$Jaccard, by = list(Hist$Group), FUN = quantile)
aggregate(HistMod$Jaccard, by = list(HistMod$Group), FUN = quantile)
aggregate(HistMod$Jaccard * 2, by = list(HistMod$Group), FUN = quantile)
head(Scatter)
dim(Scatter)
ggplot(Scatter, aes(x = Jaccard * 2, y = Paralogous.cluster)) + geom_point() + geom_abline(intercept=0, slope=1)  + xlab("Jaccard 99 percent")+ ylab("Jaccard 95 percent")
ggplot(Scatter, aes(y = Jaccard * 2, x = Paralogous.cluster)) + geom_point() + geom_abline(intercept=0, slope=1)  + xlab("Shared anch")+ ylab("Jaccard 99 percent")
ggplot(Scatter, aes(y = N95.Jaccard * 2, x = N95.Paralogous.cluster)) + geom_point()  + xlab("Shared anch")+ ylab("Jaccard 99 percent")
head(Hist)
ggplot(Scatter, aes(y = Jaccard * 2, x = Shared_anchor, fill = Group)) + geom_point()  + xlab("Shared anch")+ ylab("Jaccard 99 percent")
ggplot(Hist, aes(y = Jaccard * 2, x = Shared_anchor, fill = Group)) + geom_point()  + xlab("Shared anch")+ ylab("Jaccard 99 percent")
ggplot(Hist, aes(y = Jaccard * 2, x = Shared_anchor)) + geom_point(color = factor(Group))  + xlab("Shared anch")+ ylab("Jaccard 99 percent")
ggplot(Hist, aes(y = Jaccard * 2, x = Shared_anchor, color = Group)) + geom_point()  + xlab("Shared anch")+ ylab("Jaccard 99 percent")
ggplot(Hist, aes(y = Jaccard * 2, x = Shared_anchor, color = factor(Group))) + geom_point()  + xlab("Shared anch")+ ylab("Jaccard 99 percent")
ggplot(Hist, aes(y = Jaccard * 2, x = NormShared, color = factor(Group))) + geom_point()  + xlab("Shared anch")+ ylab("Jaccard 99 percent")
ggplot(HistMod, aes(y = Jaccard * 2, x = NormShared, color = factor(Group))) + geom_point()  + xlab("Shared anch")+ ylab("Jaccard 99 percent")
HistMod = Hist[Hist$Cluster.size > 6, ]
ggplot(HistMod, aes(y = Jaccard * 2, x = NormShared, color = factor(Group))) + geom_point()  + xlab("Shared anch")+ ylab("Jaccard 99 percent")
HistMod = Hist[Hist$Cluster.size > 10 & Hist$Cluster.size < 1000, ]
ggplot(HistMod, aes(y = Jaccard * 2, x = NormShared, color = factor(Group))) + geom_point()  + xlab("Shared anch")+ ylab("Jaccard 99 percent")
ggplot(HistMod, aes(y = Jaccard * 2, x = NormShared, color = factor(Group))) + geom_point()  + xlab("Shared anch")+ ylab("Jaccard 99 percent") + scale_y_continuous(c(0, 0.01))
ggplot(HistMod, aes(y = Jaccard * 2, x = NormShared, color = factor(Group))) + geom_point()  + xlab("Shared anch")+ ylab("Jaccard 99 percent") + scale_y_continuous(limits = c(0, 0.01))
ggplot(HistMod, aes(y = Jaccard * 2, x = Shared_anchor, color = factor(Group))) + geom_point()  + xlab("Shared anch")+ ylab("Jaccard 99 percent") + scale_y_continuous(limits = c(0, 0.01))
ggplot(HistMod, aes(y = Jaccard * 2, x = Shared_anchor, color = factor(Group))) + geom_point()  + xlab("Shared anch")+ ylab("Jaccard 99 percent") + scale_y_continuous(limits = c(0, 0.1))
ggplot(HistMod, aes(y = Jaccard * 2, x = Shared_anchor, color = factor(Group))) + geom_point()  + xlab("Shared anch")+ ylab("Jaccard 99 percent") + scale_y_continuous(limits = c(0, 1))
ggplot(HistMod, aes(y = Jaccard * 2, x = NormShared, color = factor(Group))) + geom_point()  + xlab("Shared anch")+ ylab("Jaccard 99 percent") + scale_y_continuous(limits = c(0, 1))
ggplot(HistMod, aes(y = Jaccard * 2, x = NormShared, color = factor(Group))) + geom_point()  + xlab("Shared anch")+ ylab("Jaccard 99 percent") + scale_y_continuous(limits = c(0, 0.01))
ggplot(HistMod, aes(y = Jaccard * 2, x = NormShared, color = factor(Group))) + geom_point()  + xlab("Shared anch")+ ylab("Jaccard 99 percent") + scale_y_continuous(limits = c(0, 0.1))
ggplot(HistMod, aes(y = Jaccard * 2, x = Shared_anchor, color = factor(Group))) + geom_point()  + xlab("Shared anch")+ ylab("Jaccard 99 percent") + scale_y_continuous(limits = c(0, 0.01))
head(Hist)
Hist = rbind(data.frame("Jaccard" = Score$Jaccard, "Cluster.size" = Score$Paralogous.cluster.size, "Group" = 95, "Shared_anchor" = Score$Paralogous.cluster), data.frame("Jaccard" = Score99$Jaccard, "Cluster.size" = Score99$Paralogous.cluster.size, "Group" = 99, "Shared_anchor" = Score99$Paralogous.cluster))
head(Score)
Hist = rbind(data.frame("Overlp" = Score99$Cluster.overlap,"Jaccard" = Score$Jaccard, "Cluster.size" = Score$Paralogous.cluster.size, "Group" = 95, "Shared_anchor" = Score$Paralogous.cluster), data.frame("Jaccard" = Score99$Jaccard, "Cluster.size" = Score99$Paralogous.cluster.size, "Group" = 99, "Shared_anchor" = Score99$Paralogous.cluster, "Overlp" = Score99$Cluster.overlap))
head(Hist)
HistMod = Hist[Hist$Cluster.size > 10 & Hist$Cluster.size < 1000, ]
ggplot(HistMod, aes(y = Jaccard * 2, x = Shared_anchor, color = factor(Group))) + geom_point()  + xlab("Shared anch")+ ylab("Jaccard 99 percent") + scale_y_continuous(limits = c(0, 0.01))
ggplot(HistMod, aes(y = Overlap, x = Shared_anchor, color = factor(Group))) + geom_point()  + xlab("Shared anch")+ ylab("Jaccard 99 percent") + scale_y_continuous(limits = c(0, 0.01))
Hist = rbind(data.frame("Overlap" = Score99$Cluster.overlap,"Jaccard" = Score$Jaccard, "Cluster.size" = Score$Paralogous.cluster.size, "Group" = 95, "Shared_anchor" = Score$Paralogous.cluster), data.frame("Jaccard" = Score99$Jaccard, "Cluster.size" = Score99$Paralogous.cluster.size, "Group" = 99, "Shared_anchor" = Score99$Paralogous.cluster, "Overlap" = Score99$Cluster.overlap))
HistMod = Hist[Hist$Cluster.size > 10 & Hist$Cluster.size < 1000, ]
ggplot(HistMod, aes(y = Overlap, x = Shared_anchor, color = factor(Group))) + geom_point()  + xlab("Shared anch")+ ylab("Jaccard 99 percent") + scale_y_continuous(limits = c(0, 0.01))
ggplot(HistMod, aes(y = Overlap, x = Shared_anchor, color = factor(Group))) + geom_point()  + xlab("Shared anch")+ ylab("Jaccard 99 percent")
Hist = rbind(data.frame("Overlap" = Score$Cluster.overlap,"Jaccard" = Score$Jaccard, "Cluster.size" = Score$Paralogous.cluster.size, "Group" = 95, "Shared_anchor" = Score$Paralogous.cluster), data.frame("Jaccard" = Score99$Jaccard, "Cluster.size" = Score99$Paralogous.cluster.size, "Group" = 99, "Shared_anchor" = Score99$Paralogous.cluster, "Overlap" = Score99$Cluster.overlap))
HistMod = Hist[Hist$Cluster.size > 10 & Hist$Cluster.size < 1000, ]
ggplot(HistMod, aes(y = Overlap, x = Shared_anchor, color = factor(Group))) + geom_point()  + xlab("Shared anch")+ ylab("Jaccard 99 percent")
ggplot(HistMod, aes(y = Overlap, x = Shared_anchor, color = factor(Group))) + geom_point()  + xlab("Shared anch")+ ylab("Jaccard 99 percent") + scale_y_continuous(limits = c(0, 5))
library(ggtern)
install.packages("ggtern")
install.packages("/home/ehsab/Gene_duplication/Rpackage/ggtern_1.0.3.2.tar.gz", repos=NULL, type = "source")
librray(ggtern)
library(ggtern)
random <- data.frame(T = runif(100),
                     L = runif(100),
                     R = runif(100))
random <- random/apply(random, 1, sum)
 
# For Rendering the Lines, use Segment geometry
lines <- data.frame(x = c(0.5, 0, 0.5),
                    y = c(0.5, 0.5, 0),
                    z = c(0, 0.5, 0.5),
                    xend = c(1, 1, 1)/3,
                    yend = c(1, 1, 1)/3,
                    zend = c(1, 1, 1)/3)
 
# Render.
ggtern(data = random, aes(T, L, R)) +
       geom_point() +
       geom_segment(data = lines,
                    aes(x, y, z,
                        xend = xend, yend = yend, zend = zend),
                    color = 'red', size = 1)
ggtern(data = HistMod, aes())
head(HistMod)
ggtern(data = HistMod, aes(overlap, cluster.size, Shared_anchor)) + geom_point()
ggtern(data = HistMod, aes(Overlap, cluster.size, Shared_anchor)) + geom_point()
ggtern(data = HistMod, aes(Overlap, Cluster.size, Shared_anchor)) + geom_point()
ggtern(data = HistMod, aes(Overlap, Cluster.size, Shared_anchor, color = Group)) + geom_point()
ggtern(data = Hist, aes(Overlap, Cluster.size, Shared_anchor, color = Group)) + geom_point()
ggtern(data = Hist, aes(Overlap, Cluster.size, Shared_anchor, color = Group)) + geom_point() + scale_x_continuous(limits = c(0, 1000))
ggtern(data = Hist, aes(Overlap, Cluster.size, Shared_anchor, color = Group)) + geom_point() + scale_x_continuous(limits = c(0, 1000)) + scale_x_continuous(limits = c(0, 1000)) + scale_x_continuous(limits = c(0, 1000))
ggtern(data = Hist, aes(Overlap, Cluster.size, Shared_anchor, color = Group)) + geom_point() + scale_x_continuous(limits = c(0, 1000)) + scale_z_continuous(limits = c(0, 1000)) + scale_y_continuous(limits = c(0, 1000))
ggtern(data = Hist, aes(Overlap, Cluster.size, Shared_anchor, color = Group)) + geom_point() + scale_x_continuous(limits = c(0, 1000)) + scale_z_continuous(limits = c(0, 1000))
ggtern(data = Hist, aes(Overlap, Cluster.size, Shared_anchor, color = Group)) + geom_point() + scale_x_continuous(limits = c(0, 1000)) + scale_y_continuous(limits = c(0, 1000))
lines
ggtern(data = Hist, aes(Overlap, Cluster.size, Shared_anchor, color = Group)) + geom_point()
ggtern(data = Hist, aes(Overlap, Cluster.size, Shared_anchor, color = factor(Group))) + geom_point()
head(Hist)
library(preprocess)
library(preprocessCore)
HistNorm = normalize.quantiles(Hist[, "Overlap", "Cluster.size", "Shared_anchor"])
HistNorm = normalize.quantiles(Hist[, c("Overlap", "Cluster.size", "Shared_anchor")])
HistNorm = normalize.quantiles(as.matrix(Hist[, c("Overlap", "Cluster.size", "Shared_anchor")]))
head(HistNorm)
colnames(HistNorm) = c("Overlap", "Cluster.size", "Shared_anchor")
HistNorm = as.data.frame(c("Overlap", "Cluster.size", "Shared_anchor"))
head(HistNorm)
HistNorm = normalize.quantiles(as.matrix(Hist[, c("Overlap", "Cluster.size", "Shared_anchor")]))
head(HistNorm)
colnames(HistNorm)
colnames(HistNorm) = c("Overlap", "Cluster.size", "Shared_anchor")
HistNorm = as.data.frame(HistNorm)
head(HistNorm)
HistNorm = data.frame(HistNorm, "Group" = Hist$Group)
ggtern(data = HistNorm, aes(Overlap, Cluster.size, Shared_anchor, color = factor(Group))) + geom_point()
ata(Feldspar)
aata(Feldspar)
sata(Feldspar)
data(Feldspar)
head(Feldspar)
Feldspar <- Feldspar[with(Feldspar, order(-P.Gpa)), ]
head(Feldspar)
head(HistNorm)
head(Hist)
HistScal = apply(Hist, 2, scale)
head(HistScal)
ggtern(data = HistScal, aes(Overlap, Cluster.size, Shared_anchor, color = factor(Group))) + geom_point()
HistScal = as.matrix(HistScal)
ggtern(data = HistScal, aes(Overlap, Cluster.size, Shared_anchor, color = factor(Group))) + geom_point()
HistScal = as.data.frame(HistScal)
ggtern(data = HistScal, aes(Overlap, Cluster.size, Shared_anchor, color = factor(Group))) + geom_point()
HistScal["Group"] = Hist$Group
ggtern(data = HistScal, aes(Overlap, Cluster.size, Shared_anchor, color = factor(Group))) + geom_point()
HistScal = HistScal + 10
HistScal["Group"] = Hist$Group
ggtern(data = HistScal, aes(Overlap, Cluster.size, Shared_anchor, color = factor(Group))) + geom_point()
HistScal = HistScal -8
HistScal["Group"] = Hist$Group
ggtern(data = HistScal, aes(Overlap, Cluster.size, Shared_anchor, color = factor(Group))) + geom_point()
HistScal = HistScal -1
HistScal["Group"] = Hist$Group
ggtern(data = HistScal, aes(Overlap, Cluster.size, Shared_anchor, color = factor(Group))) + geom_point()
ggplot(HistMod, aes(y = Overlap, x = Shared_anchor, color = factor(Group))) + geom_point()  + xlab("Shared anch")+ ylab("Jaccard 99 percent")
head(HistMod)
princomp(HistMod[, c(1,3,5)])
fit = princomp(HistMod[, c(1,3,5)])
fit
summary(fit)
biplot(fit)
loadings(fit)
?princomp
dim(HistScal)
dim(HistMod)
HistScal = apply(HistMod, 2, scale)
fit = princomp(HistScal[, c(1,3,5)])
summary(fit)
loadings(fit)
library(psych)
install.packages(psych)
install.packages("psych")
library(psych)
fit <- factanal(HistScal[, c(1,3,5)], 3, rotation="varimax")
fit <- factanal(HistScal[, c(1,3,5)], 2, rotation="varimax")
fit <- principal(HistScal[, c(1,3,5)], nfactors=5, rotate="varimax")
fit <- principal(HistScal[, c(1,3,5)], nfactors=3, rotate="varimax")
fit
load <- fit$loadings[,1:2] 
load
fit$loadings
plot(load,type="n")
?princomp
prc <- prcomp( HistScal[, c(1, 3, 5)], center=TRUE, scale=TRUE)
prc
varimax7 <- varimax(prc$rotation[,1:2])
varimx7
varimax7
prc <- prcomp( HistScal[, c(1, 3, 5)], center=FALSE, scale=FALSE)
prc
names(prc)
prc$rotation
fit$loadings
fit <- princomp( HistScal[, c(1, 3, 5)])
fit$loadings
fit
summary(fit)
varimax7 <- varimax(fir$loadings[,1:2])
varimax7 <- varimax(fit$loadings[,1:2])
varimax7
fit$loadings[,1:2]
newData <- HistScal[, c(1, 3, 5)] %*% varimax7$loadings
newData
head(newData)
class(newData)
newData = as.data.frame(newData)
newData["Group"] = HistScal$Group
newData["Group"] = HistScal[, "Group"]
head(newData)
newData["Group"] = Hist$Group
newData["Group"] = HistMod$Group
head(newData)
ggplot(newData, aes(x = Comp.1, y = Comp.2, color = factor(Group)) + geom_point()
)
ggplot(newData, aes(x = Comp.1, y = Comp.2, color = factor(Group))) + geom_point()
varimax7
head(Hist)
ggplot(Hist, aes(x = Overlap, y = Cluster.size, z = Shared_anchor)) + stat_contour()
library(reshape2) # for melt
volcano3d <- melt(volcano)
names(volcano3d) <- c("x", "y", "z")
head(volcano3d)
class(Hist)
sort(unique(Hist$Overlap))
sort(unique(Hist$Cluster.size))
ggplot(Hist, aes(x = Overlap, y = Cluster.size, z = Shared_anchor)) + stat_contour()
ggplot(Hist, aes(x = Overlap, y = Cluster.size, z = Shared_anchor, color = Group)) + stat_contour()
ggplot(Hist, aes(x = Shared_anchor, y = Cluster.size, z = Overlap, color = Group)) + stat_contour()
ggplot(Hist, aes(x = Shared_anchor, y = Cluster.size, z = Overlap)) + stat_contour()
ggplot(Hist, aes(x = Shared_anchor, y = Overlap, z = Cluster.size)) + stat_contour()
ggplot(HistMod, aes(y = Overlap, x = Shared_anchor, color = factor(Group))) + geom_point()  + xlab("Shared anch")+ ylab("Jaccard 99 percent") + scale_y_continuous(limits = c(0, 0.01))
dim(HistMod)
dim(Hist)
ggplot(HistMod, aes(y = Overlap, x = Shared_anchor, color = factor(Group))) + geom_point()  + xlab("Shared anch")+ ylab("Jaccard 99 percent")
ggplot(HistMod, aes(y = Overlap, x = Shared_anchor, color = factor(Group))) + geom_point()  + xlab("Shared anch")+ ylab("Overlap")
jpeg("/scratch/iwt/ehsab/Gene_duplication/Results/SA/Compare_SA__permut_thresold/abiotic/OverlapSharedAnchor.jpeg", width=8, height=5, units="in", res=100, pointsize = 5)
ggplot(HistMod, aes(y = Overlap, x = Shared_anchor, color = factor(Group))) + geom_point()  + xlab("Shared anch")+ ylab("Overlap")
dev.off()
ggplot(HistMod, aes(y = Overlap, x = Shared_anchor, color = factor(Group))) + geom_point()  + xlab("Shared anch")+ ylab("Overlap") + scale_y_continuous(limits = c(0, 10))
ggplot(HistMod, aes(y = Overlap, x = Shared_anchor, color = factor(Group))) + geom_point()  + xlab("Shared anch")+ ylab("Overlap") + scale_y_continuous(limits = c(0, 20))
ggplot(HistMod, aes(y = Jaccard, x = Shared_anchor, color = factor(Group))) + geom_point()  + xlab("Shared anch")+ ylab("Overlap") + scale_y_continuous(limits = c(0, 0.01))
ggplot(HistMod, aes(y = Jaccard, x = Shared_anchor, color = factor(Group))) + geom_point()  + xlab("Shared anch")+ ylab("Jaccard") + scale_y_continuous(limits = c(0, 0.01))
head(HistMod)
savehistory("/ngsprojects/iwt/ehsab/Gene_duplication/Scripts/SA/ComparingDifferentThresholdPermutationSA.r")
